### ISSUE TITLE
truvari options

### ISSUE THREAD

**Issue by kcleal** [HudsonAlpha/CSL_public_benchmark#10] opened 2022-02-10 10:06 UTC
Hi,
Thanks for testing dysgu, I have a few questions about whats causing the low precision values of dysgu. Firstly, I just wanted to compare notes about how you test using truvari. I have tested with:
`grep '#\|PASS' HG002.dysgu.vcf | grep '#\|DEL' > HG002.dysgu_pass.del.vcf;
bgzip HG002.dysgu_pass.del.vcf; tabix HG002.dysgu_pass.del.vcf;
truvari bench -b HG002_SVs_Tier1_v0.6.vcf.gz --includebed HG002_SVs_Tier1_v0.6_include.bed --sizemax 260000000 --giabreport -c HG002.dysgu_pass.del.vcf.gz -o truvari_dysgu_pass_only_del --pctsim 0 -s 50 --passonly`
Also was interested to know what coverage and read length your samples are.
Finally I noticed in the dysgu results the stdev of the precision values seemed very high, for example on the `hg38 GIAB masked dragmap-1.2.1` precision score was `0.4321+-0.2749`. Im not sure whats causing this, but possibly the insert size metrics are not being worked out properly? This should be available in the log file from dysgu. Thanks!

**Comment by holtjma** [comment] 2022-02-10 14:25
Oh, that's interesting... I didn't notice that when I was reviewing the results.  For the analysis, there are two main rules that are relevant:

The deletion filter rule (this boils down to fixing headers and grepping on "DEL"):
```
bcftools reheader --fai {params.main_fai} {input.vcf} | \
    gunzip -c | \
    grep "#\\|DEL" | \
    sed 's/CIEND,Number=1/CIEND,Number=2/g' | \
    sed 's/CIPOS,Number=1/CIPOS,Number=2/g' | \
    bgzip > {output.delVcf}
tabix {output.delVcf}
```
and the Truvari rule:
```
truvari \
    -b {params.truth} \
    -c {input.delVcf} \
    -o {output.truvariDir} \
    --pctsim 0.0 \
    --sizemax 1000000000 \
    --includebed {params.hc_region}
```

Digging into the results for dysgu, one of the two replicates (HALB3002754) seems to be consistently getting a much lower precision than the other, and that appears to be caused by a drastic increase in variants being labeled as false positives.  We are not currently filtering by PASS on Truvari, so I checked that first.  Of the 12160 in the file I checked, 353 are PASS and the remaining 11807 seem to be labeled with "lowProb".  Sounds like maybe I need to add a PASS-only filter to dysgu, is that something you would apply to both the Illumina and PB datasets?

We also are not explicitly setting the `-s` parameter, but this defaults to 50 so I don't think there is a functional difference.

**Comment by holtjma** [comment] 2022-02-10 15:43
Okay, sounds like this expects a PASS filter by default for evaluation then.  I added a PASS-only version (e.g. `-PO` at the end).  Does this look more in line with your expected performance for precision?  Looks like a strict increase in precision across the board, and the high variability disappeared.

[results_20220210b_delsonly.pdf](https://github.com/HudsonAlpha/CSL_public_benchmark/files/8042308/results_20220210b_delsonly.pdf)

**Comment by holtjma** [comment] 2022-02-10 17:42
Yea, that's interesting.  I'm not sure why it would be so drastically different, especially since pbmm2 is a derivation of minimap2 (at least, by my understanding).  Pre-filtering seems to be on-par with minimap2 though, so clearly something is different.

**Comment by holtjma** [comment] 2022-02-14 18:43
closing for now, feel free to re-open if something related comes up

**Closed by holtjma** 2022-02-14 18:43 UTC

**Comment by kcleal** [comment] 2022-04-18 18:25
Hi @holtjma,
I believe dysgu v1.3.10 should work with pbmm2 a bit better. Would it be possible to update dysgu for the next benchmark release. Thanks!

**Comment by holtjma** [comment] 2022-04-19 13:53
Yep, I'll see about testing it out.  Should have results either this week or next hopefully!

**Comment by holtjma** [comment] 2022-04-21 15:08
@kcleal I put up the preliminary results in this branch: https://github.com/HudsonAlpha/CSL_public_benchmark/tree/release_20220422

Let me know if that's what you expected to see

**Comment by kcleal** [comment] 2022-10-11 07:24
Thanks Matt,

The pbmm2 results look better than before which is good to see.

Best,

Kez

On 21 Apr 2022, at 16:08, Matt Holt ***@***.******@***.***>> wrote:

External email to Cardiff University - Take care when replying/opening attachments or links.
Nid ebost mewnol o Brifysgol Caerdydd yw hwn - Cymerwch ofal wrth ateb/agor atodiadau neu ddolenni.




@kcleal<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkcleal&data=05%7C01%7Cclealk%40cardiff.ac.uk%7C91ba667bdc534a02f70d08da23a8ce2f%7Cbdb74b3095684856bdbf06759778fcbc%7C1%7C0%7C637861505159918561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0maPRVZbLWS6PmupLvNHfu732xoBMomF43m7W0abKCE%3D&reserved=0> I put up the preliminary results in this branch: https://github.com/HudsonAlpha/CSL_public_benchmark/tree/release_20220422<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHudsonAlpha%2FCSL_public_benchmark%2Ftree%2Frelease_20220422&data=05%7C01%7Cclealk%40cardiff.ac.uk%7C91ba667bdc534a02f70d08da23a8ce2f%7Cbdb74b3095684856bdbf06759778fcbc%7C1%7C0%7C637861505159918561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GolDEwZtg5oxu%2BUn3epd%2Blh8Q%2BdyfiLxi3rsIwtY9%2Fo%3D&reserved=0>

Let me know if that's what you expected to see
